apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-19-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-19-api
  template:
    metadata:
      labels:
        app: covid-19-api
    spec:
      containers:
        - name: covid-19-api
          image: localhost:32000/covid-19-api:1.7.1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: mongodb-config
            - configMapRef:
                name: covid-19-api-config
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: covid-19-api-service
spec:
  type: ClusterIP
  selector:
    app: covid-19-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP