apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-19-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-19-api
  template:
    metadata:
      labels:
        app: covid-19-api
    spec:
      containers:
        - name: covid-19-api
          image: craigmiller160.ddns.net:30004/covid-19-api:1.9.2
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: covid-19-api-config
          env:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-root-password
                  key: MONGO_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: covid-19-api-service
spec:
  type: ClusterIP
  selector:
    app: covid-19-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
